---
defaultStorageEngineId: "mongodb"
logLevel: info
cellbase:
  hosts:
  - ${OPENCGA.CELLBASE.HOST}
  version: ${OPENCGA.CELLBASE.VERSION}
storageEngines:
- id: "mongodb"
  options: {}
  alignment:
    manager: "org.opencb.opencga.storage.mongodb.alignment.MongoDBAlignmentStorageManager"
    options:
      transform.region_size: 200000
      transform.coverage_chunk_size: 1000
      database.name: "opencga"
    database:
      hosts:
      - "mongodb-dev:27017"
      user: "user"
      password: "password"
  variant:
    manager: "org.opencb.opencga.storage.mongodb.variant.MongoDBVariantStorageManager"
    options:
      transform.batch_size: 200
      load.batch_size: 100
      load.bulk_size: 100
      load.compress_genotypes: true
      database.name: "opencga"
    database:
      hosts:
      - ${OPENCGA.STORAGE.VARIANT.DB.HOST}
      user: ${OPENCGA.STORAGE.VARIANT.DB.USER}
      password: ${OPENCGA.STORAGE.VARIANT.DB.PASSWORD}
- id: "hbase"
  options: {}
  alignment:
    manager: "org.opencb.opencga.storage.hbase.alignment.MongoDBAlignmentStorageManager"
    options: {}
    database:
      hosts:
      - "who-master:60000"
      user: "user"
      password: "password"
  variant:
    manager: "org.opencb.opencga.storage.hbase.variant.MongoDBVariantStorageManager"
    options: {}
    database:
      hosts:
      - "who-master:60000"
      user: "user"
      password: "password"
