---
logLevel: "INFO"
logFile: null

dataDir: "/opt/opencga/sessions"
tempJobsDir: "/opt/opencga/sessions/jobs"

admin: "admin"
password: "admin"

emailServer:
  host: "localhost"
  port: ""
  user: ""
  password: ""
  from: ""
  ssl: false

database:
  hosts:
  - "localhost"
  database: "opencga_catalog"
  user: "admin"
  password: ""
  options: {}
