---
logLevel: "INFO"
logFile: null

openRegister: true
userDefaultDiskQuota: 0

dataDir: ${OPENCGA.CATALOG.ROOTDIR}
tempJobsDir: ${OPENCGA.CATALOG.JOBS.ROOTDIR}
toolsDir: "tools"

admin:
  paswword: ""
  email: ""

monitor:
  daysToRemove: 30
  executionSleepTime: 4000
  fileSleepTime: 4000

execution:
  mode: "local"
  defaultQueue: ""
  availableQueues: ""
  toolsPerQueue: {}

emailServer:
  host: ${OPENCGA.CATALOG.MAIL.HOST}
  port: ${OPENCGA.CATALOG.MAIL.PORT}
  user: ${OPENCGA.CATALOG.MAIL.USER}
  password: ${OPENCGA.CATALOG.MAIL.PASSWORD}
  from: ""
  ssl: false

database:
  hosts:
  - ${OPENCGA.CATALOG.DB.HOSTS}
  database: ${OPENCGA.CATALOG.DB.DATABASE}
  user: ${OPENCGA.CATALOG.DB.USER}
  password: ${OPENCGA.CATALOG.DB.PASSWORD}
  options:
    authenticationDatabase: ${OPENCGA.CATALOG.DB.AUTHENTICATION_DATABASE}
