---
logLevel: "INFO"
logFile: null

sessionDuration: 12000  # number of seconds that session remains open

# Default study when -s, --study are empty, e.g. "reference_grch37:1kG_phase3"
defaultStudy: ""

# Alias to different studies, these can be fully qualified: user@project:study
#alias:
#  1kg_grch37: reference_grch37:1kG_phase3
#  exac: reference_grch37:EXAC
#  1kg_grch38: reference_grch38:1kG_phase3

# The default organism values can be defined here.
organism:
  taxonomyCode: ${OPENCGA.CLIENT.ORGANISM.TAXONOMY_CODE}
  scientificName: ${OPENCGA.CLIENT.ORGANISM.SCIENTIFIC_NAME}
  commonName: ${OPENCGA.CLIENT.ORGANISM.COMMON_NAME}
  assembly: ${OPENCGA.CLIENT.ORGANISM.ASSEMBLY}


## REST client configuration options
rest:
  host: "${OPENCGA.CLIENT.REST.HOST}"
  batchQuerySize: 200
  timeout: ${OPENCGA.CLIENT.REST.TIMEOUT}
  defaultLimit: 2000

## gRPC configuration options
grpc:
  host: "${OPENCGA.CLIENT.GRPC.HOST}"
